language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_script:
  - python setup.py develop
  - pip install pytest
  - pip install coveralls

script:
  - coverage run -m py.test tests/TestMethods.py || exit 1

after_success:
  - coveralls
  - coverage report

notifications:
  email:
    - pkelley@netflix.com
    - opticrealm@gmail.com
